In [1]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from pathlib import Path
import pandas as pd

In [2]:
!pip install flask flask-cors pyngrok

Requirement already satisfied: flask in /usr/local/lib/python3.12/dist-packages (3.1.2)
Requirement already satisfied: flask-cors in /usr/local/lib/python3.12/dist-packages (6.0.2)
Requirement already satisfied: pyngrok in /usr/local/lib/python3.12/dist-packages (7.5.0)
Requirement already satisfied: blinker>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from flask) (1.9.0)
Requirement already satisfied: click>=8.1.3 in /usr/local/lib/python3.12/dist-packages (from flask) (8.3.1)
Requirement already satisfied: itsdangerous>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from flask) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in /usr/local/lib/python3.12/dist-packages (from flask) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from flask) (3.0.3)
Requirement already satisfied: werkzeug>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from flask) (3.1.4)
Requirement already satisfied: PyYAML>=5.1 in /usr/local/lib/python3.12/dist-packages (from pyngrok) (6.0.3)

In [3]:
def replace(input_file, output_file, threshold=3):
    with open(input_file, "r", encoding="utf-8") as f_in, open(output_file, "w", encoding="utf-8") as f_out:
        for line in f_in:
            line = line.lstrip()
            semicolon_count = line.count(";")
            if semicolon_count > threshold:
                parts = line.strip().split(";")
                if len(parts) > 2:
                    between = ";".join(parts[2:-1])
                    between_clean = between.replace(";", " ")
                    new_line = ";".join(parts[:2] + [between_clean] + [parts[-1]]) + "\n"
                    f_out.write(new_line)
                else:
                    f_out.write(line )
            else:
                f_out.write(line )

In [4]:
train_path = r"c:\Users\ANAGHA\Downloads\train.csv"
test_path = r"c:\Users\ANAGHA\Downloads\test.csv"
evaluation_path = r"c:\Users\ANAGHA\Downloads\evaluation.csv"
train_df = pd.read_csv(train_path, sep=';')
test_df = pd.read_csv(test_path, sep=';')
eval_df = pd.read_csv(evaluation_path, sep=';')
display(train_df.head())
display(test_df.head())
display(eval_df.head())

,Unnamed: 0,title,text,label
0,0,Palestinians switch off Christmas lights in Be...,"RAMALLAH, West Bank (Reuters) - Palestinians s...",1
1,1,China says Trump call with Taiwan president wo...,BEIJING (Reuters) - U.S. President-elect Donal...,1
2,2,FAIL! The Trump Organization’s Credit Score W...,While the controversy over Trump s personal ta...,0
3,3,Zimbabwe military chief's China trip was norma...,BEIJING (Reuters) - A trip to Beijing last wee...,1
4,4,THE MOST UNCOURAGEOUS PRESIDENT EVER Receives ...,There has never been a more UNCOURAGEOUS perso...,0

,Unnamed: 0,title,text,label
0,0,"Live from New York, it's a Trump-Clinton remat...",NEW YORK (Reuters) - Veteran actor and frequen...,1
1,1,Catalan separatists to lose majority in tight ...,BARCELONA (Reuters) - Catalonia s independence...,1
2,2,North Carolina governor concedes election to D...,"WINSTON-SALEM, N.C. (Reuters) - North Carolina...",1
3,3,Draft Senate Iran legislation sets tough new U...,WASHINGTON (Reuters) - Draft legislation respo...,1
4,4,California governor taps U.S. Representative B...,"SACRAMENTO, Calif. (Reuters) - California Gove...",1

,Unnamed: 0,title,text,label
0,0,"Sanders back in U.S. Senate, blasts 'coloniali...",WASHINGTON (Reuters) - Democratic U.S. preside...,1
1,1,Kremlin: Syria peoples' congress being 'active...,MOSCOW (Reuters) - A proposal to convene a con...,1
2,2,Oregon Cop Convicted Of Shattering Biker’s Co...,"In a baffling fit of rage, an Oregon State Pol...",0
3,3,Twitter Erupts With Glee Over #CruzSexScandal...,The last thing any politician running for the ...,0
4,4,MUST WATCH VIDEO: Obama Tries To Trash Trump B...,This is too good to miss! Mr. Teleprompter did...,0

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [6]:
import sys
!{sys.executable} -m pip install shap lime

Requirement already satisfied: shap in /usr/local/lib/python3.12/dist-packages (0.50.0)
Requirement already satisfied: lime in /usr/local/lib/python3.12/dist-packages (0.2.0.1)
Requirement already satisfied: numpy>=2 in /usr/local/lib/python3.12/dist-packages (from shap) (2.0.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from shap) (1.16.3)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from shap) (1.6.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from shap) (2.2.2)
Requirement already satisfied: tqdm>=4.27.0 in /usr/local/lib/python3.12/dist-packages (from shap) (4.67.1)
Requirement already satisfied: packaging>20.9 in /usr/local/lib/python3.12/dist-packages (from shap) (25.0)
Requirement already satisfied: slicer==0.0.8 in /usr/local/lib/python3.12/dist-packages (from shap) (0.0.8)
Requirement already satisfied: numba>=0.54 in /usr/local/lib/python3.12/dist-packages (from shap) (0.60.0)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.12/dist-packages (from shap) (3.1.2)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.12/dist-packages (from shap) (4.15.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from lime) (3.10.0)
Requirement already satisfied: scikit-image>=0.12 in /usr/local/lib/python3.12/dist-packages (from lime) (0.25.2)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba>=0.54->shap) (0.43.0)
Requirement already satisfied: networkx>=3.0 in /usr/local/lib/python3.12/dist-packages (from scikit-image>=0.12->lime) (3.6.1)
Requirement already satisfied: pillow>=10.1 in /usr/local/lib/python3.12/dist-packages (from scikit-image>=0.12->lime) (11.3.0)
Requirement already satisfied: imageio!=2.35.0,>=2.33 in /usr/local/lib/python3.12/dist-packages (from scikit-image>=0.12->lime) (2.37.2)
Requirement already satisfied: tifffile>=2022.8.12 in /usr/local/lib/python3.12/dist-packages (from scikit-image>=0.12->lime) (2025.12.12)
Requirement already satisfied: lazy-loader>=0.4 in /usr/local/lib/python3.12/dist-packages (from scikit-image>=0.12->lime) (0.4)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->shap) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->shap) (3.6.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->lime) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->lime) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->lime) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->lime) (1.4.9)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->lime) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib->lime) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->shap) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->shap) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib->lime) (1.17.0)

In [7]:
def predict_proba_for_explainer(texts):
    # Preprocess the texts using the existing preprocess_text function
    cleaned_texts = [preprocess_text(text) for text in texts]
    # Vectorize the cleaned texts using the fitted tfidf_vectorizer
    tfidf_vectors = tfidf_vectorizer.transform(cleaned_texts)
    # Return the prediction probabilities from the trained model
    return model.predict_proba(tfidf_vectors)

In [8]:
train_df.info()
test_df.info()
eval_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24353 entries, 0 to 24352
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  24353 non-null  int64
 1   title       24353 non-null  object
 2   text        24353 non-null  object
 3   label       24353 non-null  int64
dtypes: int64(2), object(2)
memory usage: 761.2+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8117 entries, 0 to 8116
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  8117 non-null   int64
 1   title       8117 non-null   object
 2   text        8117 non-null   object
 3   label       8117 non-null   int64
dtypes: int64(2), object(2)
memory usage: 253.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8117 entries, 0 to 8116
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  8117 non-null   int64
 1   title       8117 non-null   object
 2   text        8117 non-null   object
 3   label       8117 non-null   int64
dtypes: int64(2), object(2)
memory usage: 253.8+ KB

In [9]:
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import pandas as pd
import nltk
import re
import numpy as np

nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')

lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

def preprocess_text(text):
    if not isinstance(text, str):
        return ""
    text = text.lower()
    text = re.sub(r'[^a-z\s]', '', text)
    tokens = nltk.word_tokenize(text)
    tokens = [word for word in tokens if word not in stop_words]
    tokens = [lemmatizer.lemmatize(word) for word in tokens]
    return ' '.join(tokens)

def split_columns(df, column_name):
    if column_name in df.columns:
        df[['index', 'title', 'text', 'label']] = df[column_name].str.split(';', n=3, expand=True)
        df = df.drop(columns=[column_name])
    return df

train_df = split_columns(train_df, ';title;text;label')
test_df = split_columns(test_df, ';title;text;label')
eval_df = split_columns(eval_df, ';title;text;label')

# Convert label column to numeric, coercing errors to NaN
train_df['label'] = pd.to_numeric(train_df['label'], errors='coerce')
test_df['label'] = pd.to_numeric(test_df['label'], errors='coerce')
eval_df['label'] = pd.to_numeric(eval_df['label'], errors='coerce')

# Filter out rows where label is NaN or not a number/integer before astype(int)
train_df = train_df[pd.notna(train_df['label']) & (train_df['label'].apply(lambda x: isinstance(x, (int, float))))]
test_df = test_df[pd.notna(test_df['label']) & (test_df['label'].apply(lambda x: isinstance(x, (int, float))))]
eval_df = eval_df[pd.notna(eval_df['label']) & (eval_df['label'].apply(lambda x: isinstance(x, (int, float))))]

# Convert label to integer
train_df['label'] = train_df['label'].astype(int)
test_df['label'] = test_df['label'].astype(int)
eval_df['label'] = eval_df['label'].astype(int)


train_df['cleaned_text'] = train_df['text'].apply(preprocess_text)
test_df['cleaned_text'] = test_df['text'].apply(preprocess_text)
eval_df['cleaned_text'] = eval_df['text'].apply(preprocess_text)

display(train_df.head())
display(test_df.head())
display(eval_df.head())

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

,Unnamed: 0,title,text,label,cleaned_text
0,0,Palestinians switch off Christmas lights in Be...,"RAMALLAH, West Bank (Reuters) - Palestinians s...",1,ramallah west bank reuters palestinian switche...
1,1,China says Trump call with Taiwan president wo...,BEIJING (Reuters) - U.S. President-elect Donal...,1,beijing reuters u presidentelect donald trump ...
2,2,FAIL! The Trump Organization’s Credit Score W...,While the controversy over Trump s personal ta...,0,controversy trump personal tax return continue...
3,3,Zimbabwe military chief's China trip was norma...,BEIJING (Reuters) - A trip to Beijing last wee...,1,beijing reuters trip beijing last week zimbabw...
4,4,THE MOST UNCOURAGEOUS PRESIDENT EVER Receives ...,There has never been a more UNCOURAGEOUS perso...,0,never uncourageous person white house barack o...

,Unnamed: 0,title,text,label,cleaned_text
0,0,"Live from New York, it's a Trump-Clinton remat...",NEW YORK (Reuters) - Veteran actor and frequen...,1,new york reuters veteran actor frequent host a...
1,1,Catalan separatists to lose majority in tight ...,BARCELONA (Reuters) - Catalonia s independence...,1,barcelona reuters catalonia independence movem...
2,2,North Carolina governor concedes election to D...,"WINSTON-SALEM, N.C. (Reuters) - North Carolina...",1,winstonsalem nc reuters north carolina governo...
3,3,Draft Senate Iran legislation sets tough new U...,WASHINGTON (Reuters) - Draft legislation respo...,1,washington reuters draft legislation respondin...
4,4,California governor taps U.S. Representative B...,"SACRAMENTO, Calif. (Reuters) - California Gove...",1,sacramento calif reuters california governor j...

,Unnamed: 0,title,text,label,cleaned_text
0,0,"Sanders back in U.S. Senate, blasts 'coloniali...",WASHINGTON (Reuters) - Democratic U.S. preside...,1,washington reuters democratic u presidential h...
1,1,Kremlin: Syria peoples' congress being 'active...,MOSCOW (Reuters) - A proposal to convene a con...,1,moscow reuters proposal convene congress syria...
2,2,Oregon Cop Convicted Of Shattering Biker’s Co...,"In a baffling fit of rage, an Oregon State Pol...",0,baffling fit rage oregon state police officer ...
3,3,Twitter Erupts With Glee Over #CruzSexScandal...,The last thing any politician running for the ...,0,last thing politician running presidency need ...
4,4,MUST WATCH VIDEO: Obama Tries To Trash Trump B...,This is too good to miss! Mr. Teleprompter did...,0,good miss mr teleprompter well went script app...

In [10]:
train_df.info()
test_df.info()
eval_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24353 entries, 0 to 24352
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    24353 non-null  int64
 1   title         24353 non-null  object
 2   text          24353 non-null  object
 3   label         24353 non-null  int64
 4   cleaned_text  24353 non-null  object
dtypes: int64(2), object(3)
memory usage: 951.4+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8117 entries, 0 to 8116
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    8117 non-null   int64
 1   title         8117 non-null   object
 2   text          8117 non-null   object
 3   label         8117 non-null   int64
 4   cleaned_text  8117 non-null   object
dtypes: int64(2), object(3)
memory usage: 317.2+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8117 entries, 0 to 8116
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    8117 non-null   int64
 1   title         8117 non-null   object
 2   text          8117 non-null   object
 3   label         8117 non-null   int64
 4   cleaned_text  8117 non-null   object
dtypes: int64(2), object(3)
memory usage: 317.2+ KB

In [11]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

tfidf_vectorizer = TfidfVectorizer(max_features=5000)
train_tfidf = tfidf_vectorizer.fit_transform(train_df['cleaned_text'])
train_tfidf_filtered = train_tfidf
train_labels_filtered = train_df['label']

model = MultinomialNB()
model.fit(train_tfidf_filtered, train_labels_filtered)
print("Model training complete.")

Model training complete.

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer(max_features=5000)

train_tfidf = tfidf_vectorizer.fit_transform(train_df['cleaned_text'])
test_tfidf = tfidf_vectorizer.transform(test_df['cleaned_text'])
eval_tfidf = tfidf_vectorizer.transform(eval_df['cleaned_text'])

train_tfidf_filtered = train_tfidf
test_tfidf_filtered = test_tfidf
eval_tfidf_filtered = eval_tfidf

train_labels_filtered = train_df['label']
test_labels_filtered = test_df['label']
eval_labels_filtered = eval_df['label']

In [13]:
from sklearn.metrics import accuracy_score, classification_report
import numpy as np
test_labels_filtered = np.asarray(test_labels_filtered, dtype=int)
eval_labels_filtered = np.asarray(eval_labels_filtered, dtype=int)
test_predictions = model.predict(test_tfidf_filtered)
eval_predictions = model.predict(eval_tfidf_filtered)
test_predictions = test_predictions.astype(int)
eval_predictions = eval_predictions.astype(int)


print("Test Set Evaluation:")
print("Accuracy:", accuracy_score(test_labels_filtered, test_predictions))
print("Classification Report:\n", classification_report(test_labels_filtered, test_predictions))
print("\nEvaluation Set Evaluation:")
print("Accuracy:", accuracy_score(eval_labels_filtered, eval_predictions))
print("Classification Report:\n", classification_report(eval_labels_filtered, eval_predictions))

Test Set Evaluation:
Accuracy: 0.9210299371689048
Classification Report:
               precision    recall  f1-score   support

           0       0.91      0.92      0.91      3753
           1       0.93      0.93      0.93      4364

    accuracy                           0.92      8117
   macro avg       0.92      0.92      0.92      8117
weighted avg       0.92      0.92      0.92      8117


Evaluation Set Evaluation:
Accuracy: 0.9136380436121719
Classification Report:
               precision    recall  f1-score   support

           0       0.90      0.91      0.91      3803
           1       0.92      0.91      0.92      4314

    accuracy                           0.91      8117
   macro avg       0.91      0.91      0.91      8117
weighted avg       0.91      0.91      0.91      8117

In [14]:
def predict_fake_news(news_text):
    cleaned_text = preprocess_text(news_text)
    tfidf_text = tfidf_vectorizer.transform([cleaned_text])
    prediction = model.predict(tfidf_text)
    return prediction[0]
sample_news = """
WASHINGTON—Fulfilling his pledge to realign the mission of the White House kitchen with the vision of the Founding Fathers, President Donald Trump signed an executive order this week officially renaming the White House refrigerator the U.S. Department of Ham. “When Thomas Jefferson had the first ice house installed in 1801, the name Department of Ham was chosen to show the world our ability to eat cold cuts at a moment’s notice,” said Trump at the Oval Office signing ceremony, adding that when Harry Truman changed the appliance’s name to “fridge” in 1947, it “weakened the nation’s image” and disrespected the men and women throughout the country’s history who have enjoyed fresh deli meat at any time of day. “The Department of Ham is a beautiful name that conveys tremendous strength when it comes to cured pork, and it in no way downplays the strategic importance of turkey, salami, or even pre-packaged smoked salmon. The restoration of this name will return this storied 28-cubic-foot department to its former glory.” At press time, a professional headshot of a glistening ham posed before the U.S. flag had been added to the Cabinet website.
"""
prediction = predict_fake_news(sample_news)
if prediction == 1:
    print(f"The sample news is predicted to be: Real ({prediction})")
else:
    print(f"The sample news is predicted to be: Fake ({prediction})")

The sample news is predicted to be: Fake (0)

In [15]:
results_dict = {
    'Original Text': pd.concat([test_df['text'], eval_df['text']]),
    'True Label': np.concatenate([test_labels_filtered, eval_labels_filtered]),
    'Predicted Label': np.concatenate([test_predictions, eval_predictions])
}

results_df = pd.DataFrame(results_dict)
display(results_df.head())

,Original Text,True Label,Predicted Label
0,NEW YORK (Reuters) - Veteran actor and frequen...,1,0
1,BARCELONA (Reuters) - Catalonia s independence...,1,1
2,"WINSTON-SALEM, N.C. (Reuters) - North Carolina...",1,0
3,WASHINGTON (Reuters) - Draft legislation respo...,1,1
4,"SACRAMENTO, Calif. (Reuters) - California Gove...",1,1

In [16]:
results_df.to_excel('fake_news_predictions.xlsx', index=False)

In [ ]:
import shap

# For SHAP, if using a non-tree model, we will use the KernelExplainer.
# We need a background dataset for KernelExplainer.
# It's common to use a sample of the training data for this.

# Create a background dataset for SHAP KernelExplainer
# Taking a small sample to speed up computation. You might adjust this size.
background_data = train_df['cleaned_text'].sample(100, random_state=42).tolist()
background_tfidf = tfidf_vectorizer.transform(background_data)

# Initialize JS (JavaScript) visualization in notebooks
shap.initjs()

# Initialize the KernelExplainer
# The explainer needs a prediction function that takes raw input (texts) and returns probabilities,
# and a background dataset (vectorized form).
explainer = shap.KernelExplainer(predict_proba_for_explainer, background_tfidf)

# Select a sample of test data to explain
x_test_sample = test_df['text'].sample(5, random_state=42)
x_test_sample_cleaned = x_test_sample.apply(preprocess_text)
x_test_sample_vectorized = tfidf_vectorizer.transform(x_test_sample_cleaned)

# Compute SHAP values for the sample
# The predict_proba_for_explainer function expects a list of raw texts.
shap_values = explainer.shap_values(x_test_sample_vectorized)

print("SHAP values calculated.")